---
sidebar: sidebar 
permalink: trident-use/monitor-trident.html 
keywords: telemetry, astra trident, monitor, metrics, health, volume usage, autosupport 
summary: 'Astra Trident fournit un ensemble de terminaux de metrics de Prometheus que vous pouvez utiliser pour surveiller les performances d"Astra Trident.' 
---
= Contrôle d'Astra Trident
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ASTRA Trident fournit un ensemble de terminaux de metrics Prometheus que vous pouvez utiliser pour contrôler les performances d'Astra Trident.



== Présentation

Avec les metrics d'Astra Trident, vous pouvez :

* Surveillez l'état et la configuration d'Astra Trident. Vous avez la possibilité d'examiner la réussite des opérations et de savoir si elles peuvent communiquer avec les systèmes back-end comme prévu.
* Examiner les informations d'utilisation du système back-end et comprendre le nombre de volumes provisionnés sur un système back-end, ainsi que la quantité d'espace consommé, etc.
* Conservez un mappage de la quantité de volumes provisionnés sur les systèmes back-end disponibles.
* Suivi des performances. Découvrez le temps nécessaire pour communiquer avec Astra Trident aux systèmes back-end et effectuer les opérations.



NOTE: Par défaut, les mesures de Trident sont exposées sur le port cible `8001` au niveau du `/metrics` noeud final. Ces mesures sont *activées par défaut* lors de l'installation de Trident.

.Ce dont vous avez besoin
* Cluster Kubernetes avec Astra Trident installé.
* Instance Prometheus. Ce peut être un https://github.com/prometheus-operator/prometheus-operator["Déploiement conteneurisé par Prometheus"^] ou vous pouvez choisir d'exécuter Prometheus comme un https://prometheus.io/download/["application native"^].




== Étape 1 : définir une cible Prometheus

Vous devez définir une cible Prometheus pour collecter les metrics et obtenir des informations sur les systèmes back-end gérés par Trident, les volumes qu'elle crée, etc.  https://netapp.io/2020/02/20/prometheus-and-trident/["Blog"^]Vous apprendrez ainsi à utiliser Prometheus et Grafana avec Astra Trident pour récupérer des metrics. Découvrez sur ce blog comment exécuter Prometheus en tant qu'opérateur dans votre cluster Kubernetes et comment créer un ServiceMonitor pour obtenir des metrics Astra Trident.



== Étape 2 : créer un ServiceMonitor Prometheus

Pour consommer les metrics Trident, vous devez créer un ServiceMonitor Prometheus qui surveille le `trident-csi` service et écoute sur le `metrics` port. Un exemple de ServiceMonitor se présente comme suit :

[listing]
----
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: trident-sm
  namespace: monitoring
  labels:
      release: prom-operator
spec:
  jobLabel: trident
  selector:
    matchLabels:
      app: controller.csi.trident.netapp.io
  namespaceSelector:
    matchNames:
    - trident
  endpoints:
  - port: metrics
    interval: 15s
----
Cette définition de ServiceMonitor récupère les mesures renvoyées par le `trident-csi` service et recherche spécifiquement le `metrics` point final du service. Par conséquent, Prometheus est désormais configuré pour être en mesure de comprendre les metrics d'Astra Trident.

En plus des metrics disponibles directement depuis Astra Trident, kubelet expose de nombreux `kubelet_volume_*` metrics via son propre terminal de metrics. Kubelet peut fournir des informations sur les volumes reliés, ainsi que sur les pods et autres opérations internes qu'elle gère. Reportez-vous à la https://kubernetes.io/docs/concepts/cluster-administration/monitoring/["ici"^].



== Étape 3 : interroger les mesures Trident avec PromQL

PromQL est bon pour la création d'expressions qui renvoient des séries chronologiques ou des données tabulaires.

Voici quelques questions PromQL que vous pouvez utiliser :



=== Accédez aux informations sur l'état de santé de Trident

* **Pourcentage de réponses HTTP 2XX d'Astra Trident**


[listing]
----
(sum (trident_rest_ops_seconds_total_count{status_code=~"2.."} OR on() vector(0)) / sum (trident_rest_ops_seconds_total_count)) * 100
----
* **Pourcentage de réponses REST d'Astra Trident par le code d'état**


[listing]
----
(sum (trident_rest_ops_seconds_total_count) by (status_code)  / scalar (sum (trident_rest_ops_seconds_total_count))) * 100
----
* **Durée moyenne en ms des opérations effectuées par Astra Trident**


[listing]
----
sum by (operation) (trident_operation_duration_milliseconds_sum{success="true"}) / sum by (operation) (trident_operation_duration_milliseconds_count{success="true"})
----


=== Découvrez les informations d'utilisation d'Astra Trident

* **Taille moyenne du volume**


[listing]
----
trident_volume_allocated_bytes/trident_volume_count
----
* **Espace volume total provisionné par chaque back-end**


[listing]
----
sum (trident_volume_allocated_bytes) by (backend_uuid)
----


=== Utiliser individuellement le volume


NOTE: Cette activation est uniquement possible si les indicateurs kubelet sont également collectés.

* **Pourcentage d'espace utilisé pour chaque volume**


[listing]
----
kubelet_volume_stats_used_bytes / kubelet_volume_stats_capacity_bytes * 100
----


== Découvrez la télémétrie AutoSupport d'Astra Trident

Par défaut, Astra Trident envoie des metrics de Prometheus et des informations de base back-end à NetApp dans un rythme quotidien.

* Pour empêcher Astra Trident d'envoyer des metrics Prometheus et des informations back-end de base à NetApp, transmettez le `--silence-autosupport` drapeau lors de l'installation d'Astra Trident.
* ASTRA Trident peut également envoyer des journaux de conteneur à NetApp support à la demande via `tridentctl send autosupport`. Vous devrez déclencher Astra Trident pour télécharger ses journaux. Avant de soumettre des journaux, vous devez accepter les fichiers NetApp https://www.netapp.com/company/legal/privacy-policy/["politique de confidentialité"^].
* Sauf mention contraire, Astra Trident extrait les journaux des 24 dernières heures.
* Vous pouvez spécifier la durée de conservation du journal avec l' `--since`indicateur. Par exemple : `tridentctl send autosupport --since=1h`. Ces informations sont collectées et envoyées via un `trident-autosupport` conteneur installé avec Astra Trident. Vous pouvez obtenir l'image du conteneur à l'adresse https://hub.docker.com/r/netapp/trident-autosupport["AutoSupport Trident"^].
* Le AutoSupport Trident ne collecte pas et ne transmet pas d'informations à caractère personnel (PII) ou de données personnelles. Il est fourni avec un https://www.netapp.com/us/media/enduser-license-agreement-worldwide.pdf["CLUF"^] qui ne s'applique pas à l'image du conteneur Trident. Pour en savoir plus sur l'engagement de NetApp en faveur de la sécurité et de la confiance des données https://www.netapp.com/pdf.html?item=/media/14114-enduserlicenseagreementworldwidepdf.pdf["ici"^].


Voici un exemple de charge utile envoyée par Astra Trident :

[listing]
----
---
items:
- backendUUID: ff3852e1-18a5-4df4-b2d3-f59f829627ed
  protocol: file
  config:
    version: 1
    storageDriverName: ontap-nas
    debug: false
    debugTraceFlags:
    disableDelete: false
    serialNumbers:
    - nwkvzfanek_SN
    limitVolumeSize: ''
  state: online
  online: true

----
* Les messages AutoSupport sont envoyés au terminal AutoSupport de NetApp. Si vous utilisez un registre privé pour stocker des images de conteneur, vous pouvez utiliser l' `--image-registry`indicateur.
* Vous pouvez également configurer des URL proxy en générant les fichiers YAML d'installation. Ceci peut être fait en utilisant `tridentctl install --generate-custom-yaml` pour créer les fichiers YAML et en ajoutant l' `--proxy-url`argument pour le `trident-autosupport` conteneur dans `trident-deployment.yaml`.




== Désactivation des metrics d'Astra Trident

Pour que **disable** metrics ne soient pas signalés, vous devez générer des YAML personnalisés (à l'aide de `--generate-custom-yaml` l'indicateur) et les modifier pour supprimer l' `--metrics`indicateur d'appel pour le `trident-main` conteneur.
